CREATE DATABASE BANK_OF_ZSGS;

USE BANK_OF_ZSGS;

CREATE TABLE CUSTOMER_DETAILS(
	AccNo SMALLINT PRIMARY KEY AUTO_INCREMENT,
    Customer_Name VARCHAR(30) NOT NULL,
    Gender VARCHAR(10) NOT NULL,
    Contact_Number BIGINT UNIQUE NOT NULL,
    DOB VARCHAR(15) NOT NULL,
    PAN_Card VARCHAR(10) UNIQUE NOT NULL,
    UPI_ID VARCHAR(30) UNIQUE NOT NULL,
    Password VARCHAR(20) NOT NULL,
    UPI_PIN VARCHAR(5) NOT NULL
)AUTO_INCREMENT = 1001;

CREATE TABLE AccNo_PASSBOOK(
	SlNo INT PRIMARY KEY AUTO_INCREMENT,
    AccNo SMALLINT NOT NULL,
    Date_and_Time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Debit FLOAT(9,2) DEFAULT 0,
    Credit FLOAT(9,2) DEFAULT 0,
    Available_Balance FLOAT(9,2) DEFAULT 0
);